[package]
name = "rlox"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]
authors = ["xiuxiubiu <xiuxiubiu@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
